language: go

script:
  - make
  - ./bin/benpaoba
  - ./bin/benpaoba --version
  - ./bin/benpaoba --help

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: IBroPlQ/DwSD+2xP9Cu+6nMI9Rgse2ueWGUuHpgbv7mWtXs9hOPxIa1fzHQxAYcWMRLgVSWXZfUdoKd2rTE1i9WFfoLTK9fkzxAYHBcVatvHf5g9g1/tD+4bKGWG199Puv5PpJyo2KIhmLVvpRVlF4ndu1E1e4DogaGQi01EwK6A2cvoF3YyG9TWubFEsauLj4WsG4aLMjTvTZp4JJldvVUZ+ShGtRtBZ1qy+uxhKRi13xn7ULQxkBY3oTfNv2SbRq/dmcGqnvj287KpnW/D0md73r4NeBc6cqRIxPQATa04NpMTRk2/SLNlT9ioSC1FnnhakqhIMtD0FDYdS0cddGhTClumSQEMGbhN7t343PAQuGkPn/+JfGDNWm/NxXVpPPaydO69Ewm7Izrah/GhC5hUacBORbfu5ekeSH2+PLg2JXBg2vnHznEn9MsfW2wdUJR5xTvzDU1HB0dKBe1xx5keOC6CQvl2X+jrVG0eMGRN/k0HGf46LllpTGRDdIpXJd9+qRu3uNT3GBY1eBdk6II3j90myDIOWluJkz7Yp1iAkoOgexkmMgOWm7brD02Hkj2jUvDu0ilUG1dMpf+zKmddxX4nwYjt8oB71HtCxGEjU72VC0mbU5OME8ACVBd14GBtLm3QOYF3vqkuCBo70Nuv/7pWDZHME9wuFvHkq1Y=
  file: ./bin/benpaoba
  on:
    all_branches: true
